import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/hero-1.jpg',
    title: 'Android Development from Zeo to Hero',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/hero-2.jpg',
    title: 'UI/UX Complete Guide',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/hero-3.jpg',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  // {
  //   id: 4,
  //   cover: '/images/courses/hero-4.jpg',
  //   title: 'The Complete Guide Docker and Kubernetes',
  //   rating: 4,
  //   ratingCount: 12,
  //   price: 30,
  //   category: 'Intermediate',
  // },
  // {
  //   id: 5,
  //   cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
  //   title: 'Modern React with MUI & Redux',
  //   rating: 4,
  //   ratingCount: 32,
  //   price: 35,
  //   category: 'Intermediate',
  // },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //   category: 'Beginner',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  // },
]
